config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'

  resources :users

  resources :locations do
    resources :visits
  end 

  get 'home' => 'home#welcome'
  get 'contact' => 'home#contact'

end

app/models/location.rb
class Location < ActiveRecord::Base

  has_many :visits
  validates :name, presence: true, length: { maximum: 30 }, format: { with: /[:alnum:]/ }
  validates :city, presence: true

  def self.iron_find(id)
    self.find id
  end

  def self.last_created(limit = 10)
    Location.order(created_at: :desc).limit(limit)
  end

  def total_visits_in_month_of_year(month, year)
    d = DateTime.new(year, month, 01)
    self.visits.where(['from_date >= ? AND to_date < ?', d, d.end_of_month]).count
  end

end

app/models/user.rb
class User < ActiveRecord::Base

validates :name, presence: true
validates :location_id, presence: true
validates :visit_id, presence: true

validate :premium_false_for_default
# validate :default_premium

# def default_premium
#     self.premium ||= false

# end

def premium_false_for_default
  unless premium.present?
    premium = false
  end
end

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :location

  validates :from_date, presence: true
  validates :to_date, presence: true
  validates :user_name, presence: true, format: { with: /[[:alnum:]]/ }
  validates_associated :location

  validate :from_date_is_before_to_date
  validate :from_date_is_future

  def from_date_is_future
    if from_date.to_i < Time.now.to_i
      errors.add(:from_date, "must be in the future")
    end
  end

  def from_date_is_before_to_date
    if from_date.to_i > to_date.to_i
      errors.add(:from_date, "can't be after to date")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/form_controller.rb
class FormController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end

  def contact
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.last_created(10)
  end

  def show
    @location = Location.find_by(id: params[:id])
    render '404', status: 404 unless @location
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
     
     @user = User.new(user_params)

    if @user.save
      redirect_to action: 'index', controller: 'users'
    else
      render 'new'

    end
  end

   private

  def user_params
    params.require(:user).permit(:name, :location_id, :visit_id, :premium)
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController


  def index
    @visits = Location.find(params[:location_id]).visits
  end

  def show
    @visit = Visit.find(params[:id])
  end

  def new
    #declarar las variables que llama el form si no hara crash
    @visit = Visit.new 
    @location = Location.find(params[:location_id])

  end

  def create
    @location = Location.find(params[:location_id])
    @visit = @location.visits.new(visit_params)

    if @visit.save
      redirect_to action: 'index', controller: 'visits', location_id: @location.id
      flash[:notice] = 'Thanks for creating a new visit :)'
    else
      flash[:alert] = 'ERROR DETECTED MAYDAY'
      render 'new'

    end
  end

  def destroy
    @location = Location.find(params[:location_id])
    @visit = Visit.find(params[:id])
    @visit.destroy

    if @visit.destroy
      redirect_to action: 'index', controller: 'visits', location_id: @location.id
    else 
      render 'new'
    end
  end

  def edit
    @location = Location.find(params[:location_id])
    @visit = Visit.find(params[:id])
  end

  def update
    @location = Location.find(params[:location_id])
    @visit = Visit.find(params[:id])


    if @visit.update(visit_params)
      redirect_to action: 'index', controller: 'visits', location_id: @location.id
    else
      render 'edit'
    end
  end

   private

  def visit_params
    params.require(:visit).permit(:user_name, :from_date, :to_date)
  end


 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visit_helper.rb
module VisitHelper

  def flash_message
    if flash[:error]
      flash[:error]
    elsif flash[:alert]
      flash[:alert]
    end
  end
end

app/views/home/contact.html.erb
<h1>Contact form</h1>

<form>
  <input type="text">
  <input type="textarea">
</form>

<a href="mailto:ricard.solecasas@gmail.com?subject=hi">Say hi</a>

app/views/home/welcome.html.erb
<h1>Welcome to MeetMe</h1>

<p>Your place to tell your friends where they can meet you!</p>

<%= link_to 'find friends', users_path %>
<%= link_to 'sign me up!', new_user_path %>

app/views/layouts/404.html.erb
"Not found"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'home', root_path %>

<%= link_to 'people', users_path %>

<%= yield %>

<p>2014 Meet Me Inc. All rights reserved.</p>
</body>
</html>

app/views/locations/404.html.erb
Not found

app/views/locations/index.html.erb
<h1>Locations#index</h1>

<ul>
<% @locations.each do |l| %>
  <li>
   <%= l.name %>
   <% if l.name.present? && l.city.present? %> - <% end %>
   <small><%= l.city %></small>
   -

   <%= link_to 'View visits', location_visits_path(l) %>
   <%= link_to '- Create visit', new_location_visit_path(l) %>
    <!-- Magic of ruby, you can write the above instead of this one <a href='<%= location_visits_path(l) %>'>View visits</a> -->
   </li>
<% end %>
</ul>

app/views/locations/show.html.erb
<h1>Locations#show</h1>

<h3><%= @location.name %></h3>
<p><%= @location.city %></p>

app/views/users/index.html.erb
<h1>HELLO USERS</h1>

<% unless @users.blank? %>
  <ul>
    <% @users.each do |u| %>
    <li>
      <%= u.name %> - <%= u.location_id %> - <%= u.visit_id %> - <%= u.premium %>
    </li>
    <% end %>
  </ul>

<% end %>

app/views/users/new.html.erb
<h1>NEW USER</h1>

<%= form_for [@user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :location_id %>
  <%= f.text_field :location_id %>
  <br/>
  <%= f.label :visit_id %>
  <%= f.text_field :visit_id %>
  <br/>
  <%= f.label :premium %>
  <%= f.text_field :premium %>

  <%= f.submit 'Create user' %>
  
<% end %>

app/views/visits/_form.html.erb
<%= flash_message %>

<% if @visit.errors.any? %>
  <ul>
  <% @visit.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
   <% end %>
  </ul>
<% end %>


<%= form_for [@location, @visit] do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br/>
  <%= f.datetime_select(:from_date, default: Time.now + 1.days) %>
  <br/>
  <%= f.datetime_select(:to_date, default: Time.now + 1.days) %>
  <br/>
  <%= f.submit 'Submit' %>
  
<% end %>

app/views/visits/edit.html.erb
<h2>Edit your visit</h2>

<%= render 'form' %>

app/views/visits/index.html.erb
<%= flash[:notice] %>
<h1>Visits#index</h1>

<% unless @visits.blank? %>
<ul>
  <% @visits.each do |v| %>
  <li>
      <%= v.user_name %> - <%= v.location.name %> - <%= link_to 'Cancel visit', [v.location, v], confirm: 'Are you sure you want to remove this visit? This cannot be undone.', :method => :delete %>
        <%= link_to 'Edit visit', edit_location_visit_path(v.location, v)  %>
  </li>
  <% end %>
</ul>
<% else %>
<h3>No visits!</h3>
<% end %>

<%= link_to 'Back to locations', locations_path() %>

app/views/visits/new.html.erb
<h2>New visit</h2>

<%= render 'form' %>

app/views/visits/show.html.erb
<h1>Visits#show</h1>

<h3><%= @visit.location.name %></h3>
<h5><%= @visit.user_name %></h5>
From <date><%= @visit.from_date %></date> to <date><%= @visit.to_date %></date>